package constants

const TranId = "tranId"
const UserId = "userId"
const ReqCtx = "reqCtx"
const Logger = "logger"
const BadReq = "bad request"
const Unauthorized = "unauthorized"
const InternalServiceError = "internal service error"
const NotFound = "not found"
const MethodNotAllowed = "method not allowed"
const Password = "password"
const CreatedDateTime = "createdDateTime"
const UpdatedDateTime = "updatedDateTime"
const Post = "POST"
const Head = "HEAD"
const Get = "GET"
const Put = "PUT"
const Patch = "PATCH"
const Delete = "DELETE"
